### ISSUE TITLE
Si ejecuto el tablero en proceso...

### ISSUE THREAD

**Issue by MARSFOREVER472** [MARSFOREVER472/TicTacToePokemon#2]
Me salieron unas imágenes muy grandes de dicho tablero y que no se podían ver completas, he creado este algoritmo de manera dinámica pero definitivamente me salían todos los cuadros con una imagen muy grande y distorsionada, qué puedo hacer?

Ojalá mi querido anfitrión (Autinfit) pueda resolver esto!

Gracias!

MARSFOREVER472

**Comment by Autinfit** [comment]
Hola, estimado MARSFOREVER472!

Gracias por preguntarme, justamente lo que hiciste respecto a un algoritmo de manera dinámica dentro de un ciclo "for" para las columnas, lo más probable es que si salieron ese tipo de imágenes más grande, es que yo aconsejaría el tipo de tamaño que, en vez de lo que pusiste en el algoritmo dentro de dicho ciclo el tipo "AutoSize", debiera ser reemplazado por un "StretchImage" para que la imagen pueda ver completada y enderezada sin problemas.

Espero te sirva de ayuda, estimado!

Gracias!

Autinfit

**Comment by MARSFOREVER472** [comment]
Muchas gracias, estimado!

Ahí lograste resolver esa duda, se lo arreglo de inmediato!

Gracias y saludos!
